### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by vijaykarthik123** [hgiddenss/CST_App#1]
Good job in building an OOP toolbox like this. Do you know of a way to add more methods to the Class to add more functionality? I'd happy to contribute. 
-Vijay

**Comment by hgiddenss** [comment]
Hi Vijay, 
Sorry this is pretty much the slowest reply ever (I didn't see your comment). I have been updating the code but publishing updates to  the mathworks FEX. The latest version can do much more than the original I tagged on here last June. https://uk.mathworks.com/matlabcentral/fileexchange/67731-hgiddenss-cst_app
If your still interested in the code, then feel free to fork the repository and create pull request for any suggested updates. If there are any specific features you'd like to see then please let me know.

**Comment by vijaykarthik123** [comment]
Sorry, @hgiddenss for my delayed response and thanks for your reply. We needed the code to work then (at the time of commenting), and so I wrote a script with the APIs that CST provides in their help section. I defined regular MATLAB functions to do the interaction with CST.

But privately, I'd like to help you improve its functionality. I will fork it with my personal Github account and send you a pull request from there.

Cheers!

**Comment by hgiddenss** [comment]
Hi @vijaykarthik123 ,
No problem. As I stated, the latest code here has been updated quite significantly since the I initially created the repository. The example files should show most the functionality I have included, but if there is anything missing which you specifically need (I haven't included any simple functions for retrieving H-fields/Surface currents for example) then please let me know.

**Comment by vijaykarthik123** [comment]
Thank you and sure!
-Vijay
