### ISSUE TITLE
Setting up tangent loss

### ISSUE THREAD

**Issue by mikhal7** [hgiddenss/CST_App#6]
Dear @hgiddenss ,
It appears that the expression in brackets determines the color, not the tangent loss:

` CST.addNormalMaterial('substrate_dielectric',2.7,1,[0.8 0.2 0.3]);`

Could you please add an example with a lossy material?

**Comment by hgiddenss** [comment]
Dear @mikhal7 
The loss is included as an optional argument. In order to add loss you can use:

`CST.addNormalMaterial('substrate_dielectric',2.7,1,[0.8 0.2 0.3],'tanD',0.01);`

Optional arguments are 'tand', 'sigma', 'tandM', 'sigmaM', all of which have a default value of 0
Any of the arguments can be CST parameters and can be input as strings, as long as the string represents a parameter that already exist in the CST Parameter List
